### ISSUE TITLE
Hunter pet life

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#16]
**Describe the bug**
Hunter pets life is not calculated correctly, especially seen when buffing it and remounting.

**To Reproduce**
1. Summon Hunter Pet
2. Buff it with anything increasing its life ([Spiced Mammoth Treats] [Runescroll of Fortitude])
3. See its life rising for a huge amount.
4. Mount up
5. Mount down
6. See the life beeing lowered heavily
7. Repeat everything starting from step 2

**Expected behavior**
Life not going down after mounting.

**Screenshots**
Not needed.

**Additional context**
:)

**Comment by D-CellX** [comment]
Fixed, going to apply the fix tonight thank you

**Comment by someNub** [comment]
Seems not fixed yet, bug still appears for me.

**Comment by TonyFonTony** [comment]
I know we had issues with pet talents effecting health as well when this issue was first discovered. I think it had something to do with stamina (1 point) not counting as 10 hp like it's supposed to (for pets). Not sure if that has anything to do with THIS issue, but I will do some in depth research on what stamina does on pets later today.

**Comment by D-CellX** [comment]
@TonyFonTony and I will look in to this

**Comment by Lordmatsi** [comment]
Hunter pet life seems a bit low in general if you ask me :/
![WoWScrnShot_042719_145637](https://user-images.githubusercontent.com/49250483/56850048-43803100-68fd-11e9-81a8-f10a882f1ff7.jpg)

**Comment by Lordmatsi** [comment]
Gotten anywhere on this problem?

**Comment by D-CellX** [comment]
this seems to be related to #40 
We are trying to resolve the issue and will update shortly
