### ISSUE TITLE
Ghoul

### ISSUE THREAD

**Issue by MeVeryConfusion** [RR2739-VCN/Redrum-PvP#29]
Gnaw can't be used instantly on macro, your pet automaticly places spell Claw as prior.
(Even of automatic, its random usage.)

Summon Ghoul.
Make a macro for Gnaw.
Try Gnaw macro on your target, mid fight.

When you use Gnaw macro and your Ghoul has enough energy it should activate your Ghouls Gnaw skill instantly, stunning your chosen target.

**Comment by TonyFonTony** [comment]
_Gnaw_ (in a macro and the regular spell button) seems to work fine. When _Claw_ is set to "Automatic" it will be cast as soon as it's able (spell cooldown, GCD and energy). If you attempt to use your _Gnaw_ macro at the same time that your ghoul attempts to (automatically) use _Claw_, he will use _Claw_ first and his spells will be put on GCD. There is a very small window to actually use a _Gnaw_ macro with spells set to "Automatic" but it works as intended since both spells use energy and are on the GCD.

All of this only applies when _Claw_ is set to "Automatic". When your ghoul spells are set to "Not Automatic", a _Gnaw_ macro works perfectly and instantly.

**Comment by D-CellX** [comment]
Confirmed and tested

**Comment by MeVeryConfusion** [comment]
Interesting.
