### ISSUE TITLE
Hunter Traps Disappear

### ISSUE THREAD

**Issue by someNub** [RR2739-VCN/Redrum-PvP#41]
**Describe the bug**
Hunter traps **very often** disappear when enemies walk through.

**To Reproduce**
1. Place traps
2. Let enemies walk through
3. Often traps just disappear

**Expected behavior**
Traps should trigger most of the time.

**Comment by TonyFonTony** [comment]
They disappear because they are resisted by the enemy.

I tested about 20 of each trap and only 1 was resisted total, and that was by a mage with bonus resistance from Mage Armor and Gift of the Wild. The other characters that walked through the traps didn't resist any of them. I wouldn't say it happens "very often" but if more people complain I will test further.
