### ISSUE TITLE
Quest (The road to the citadel)

### ISSUE THREAD

**Issue by chelu007** [RR2739-VCN/Redrum-PvP#74]
**Describe the bug**

The road to citadel custom quest.
High Invoker Basaleph, on which we need 5 kills to complete the quest, is not spawned.
In order for us to spawn him the normal way, we would have to do a chain quest for which the start NPC is missing. Also i think it was not meant to be done like that so i guess you just forgot to set a spawn time.

Yours truly, Markarth

**Comment by D-CellX** [comment]
Not sure exactly what you mean by "forgot to set a spawn time" since its handled by the core.

Please edit your report and follow the Bug Template thats auto added to your report upon creating it. Provide screenshots to the quest and NPC in question. The template explains how to correctly open an issue report.

High Invoker Basaleph is not part of kill credit. I suggest deleting your cache folder. 
We do not have the same Spawn ID or creature IDs as other servers, we use our own entries, maybe cached from another server. Deleting your cache folder should fix it self out.

**Comment by D-CellX** [comment]
![image](https://user-images.githubusercontent.com/47407621/64358239-f30b9500-cfba-11e9-8efd-d8ac8be38d71.png)
